
JP.ML = {

    Init: function (lang) {
        if (!JP.ML[lang]) return;

        for (var i in JP.ML[lang]) {
            JP.ML[i] = JP.ML[lang][i];
        }

        JP.emit('TextsInitialized', lang);
    },


    en: {
        Exit: 'Exit',
        Chat: 'Chat',
        GameSettings: 'Game Settings',
        MusicPlayer: 'Music Player',
        LoginWithFacebook: 'Login using Facebook',
        LoginWithTwitter: 'Login using Twitter',
        LoginWithOdno: 'Login using Однокласники',
        LoginWithVK: 'Login using Вконтакте',
        LoginWithGoogle: 'Login using Google',
        CloseSettings: 'Close',
        DisableAudioEffects: 'Disable Audio Effects',
        EnableAudioEffects: 'Enable Audio Effects',
        ClearChat: 'Clear Chat',
        ChatInputPlaceholder: 'Press enter & type message',
        ChatInputPlaceholderDisabled: 'Only emotions allowed',
        SendEmotions: 'Send Emotions',
        CloseEmotions: 'Close',
        VIPEmotions: 'VIP Emotions',
        CloseProfile: 'Close',
        RealtionStatusYou: 'It\'s You',
        RealtionStatusFriend: 'Your Friend',
        RealtionStatusFriendRequestSent: 'Friend request is sent...',
        RealtionStatusStranger: 'Send friend request',
        InviteFriend: 'Invite friends using this link & play with them:',
        CopyLink: 'Copy',
        FriendRequestMessage: 'Let\'s be friends...',
    },
    ge: {
        Exit: 'გამოსვლა',
        Chat: 'ჩატი',
        GameSettings: 'კონფიგურაცია',
        MusicPlayer: 'მუსიკა',
        LoginWithFacebook: 'შესვლა Facebook-ით',
        LoginWithTwitter: 'შესვლა Twitter-ით',
        LoginWithOdno: 'შესვლა Однокласники-ით',
        LoginWithVK: 'შესვლა Вконтакте-ით',
        LoginWithGoogle: 'შესვლა Google-ით',
        CloseSettings: 'დახურვა',
        DisableAudioEffects: 'აუდიო ეფექტების გათიშვა',
        EnableAudioEffects: 'აუდიო ეფექტების ჩართვა',
        ClearChat: 'ჩატის გასუფთავება',
        ChatInputPlaceholder: 'დააჭირეთ enter & მისწერეთ',
        ChatInputPlaceholderDisabled: 'მხოლოდ ემოციების გაგზავნა',
        SendEmotions: 'გაუგზავნეთ ემოციები',
        CloseEmotions: 'დახურვა',
        VIPEmotions: 'VIP ემოციები',
        CloseProfile: 'დახურვა',
        RealtionStatusYou: 'თქვენ',
        RealtionStatusFriend: 'თქვენი მეგობარი',
        RealtionStatusFriendRequestSent: 'მეგობრობის თხოვნა გაგზავნილია...',
        RealtionStatusStranger: 'მეგობრობის შეთავაზება',
        InviteFriend: 'გაუზიარე მეგობრებს ეს ლინკი და ეთამაშე მათ:',
        CopyLink: 'კოპირება',
        FriendRequestMessage: 'ვიმეგობროთ...',
    },
    ru: {
        Exit: 'Выход',
        Chat: 'Чат',
        GameSettings: 'Настройки игры',
        MusicPlayer: 'Музыкальный плеер',
        LoginWithFacebook: 'Войти с помощью Facebook',
        LoginWithTwitter: 'Войти с помощью Twitter',
        LoginWithOdno: 'Войти с помощью Однокласники',
        LoginWithVK: 'Войти с помощью Вконтакте',
        LoginWithGoogle: 'Войти с помощью Google',
        CloseSettings: 'Закрыть',
        DisableAudioEffects: 'Отключить звуковые эффекты',
        EnableAudioEffects: 'Включить звуковые эффекты',
        ClearChat: 'Очистить чат',
        ChatInputPlaceholder: 'Нажмите enter & введите сообщение',
        ChatInputPlaceholderDisabled: 'Только эмоции разрешено',
        SendEmotions: 'Отправить Эмоции',
        CloseEmotions: 'Закрыть',
        VIPEmotions: 'VIP Эмоции',
        CloseProfile: 'Закрыть',
        RealtionStatusYou: 'Это Вы',
        RealtionStatusFriend: 'Ваш друг',
        RealtionStatusFriendRequestSent: 'Друг просьба отправлена ...',
        RealtionStatusStranger: 'Отправить запрос о дружбе',
        InviteFriend: 'Пригласить друзей по этой ссылке и играть с ними:',
        CopyLink: 'Копировать',
        FriendRequestMessage: 'Будем друзьями...',
    },
}